vich_uploader:
    db_driver: orm

    mappings:
        providers_documents:
            uri_prefix: /providers/documents
            upload_destination: '%kernel.project_dir%/public/providers/documents'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        vehicles_images:
            uri_prefix: /vehicles/images
            upload_destination: '%kernel.project_dir%/public/vehicles/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
